"Plug 'cocopon/iceberg.vim'
"Plug 'jdsimcoe/abstract.vim'
"Plug 'arcticicestudio/nord-vim'
"Plug 'joshdick/onedark.vim'
"Plug 'rakr/vim-one'
Plug 'sainnhe/sonokai'
Plug 'junegunn/seoul256.vim'
"Plug 'sickill/vim-monokai'
